fix CellStateStyles
maxGraph/maxGraph pull request #78
Opened 2022-02-13 05:58 UTC by cd-yang

**Summary**
Property 'edge' does not exist on type 'CellStateStyles', which is used in file 'ElbowEdgeHandler' and 'EdgeHandler'

**Description for the changelog**
Added 'edge' property to 'CellStateStyles'.

2022-02-18 05:30 UTC, tbouffard requested changes
The GitHub action didn't detect the issue earlier but I can see the tsc error in my IDE 😢 
So thanks @cd-yang for the detection of the problem and your contribution!

The `CellStateStyles` `edge` property has been renamed into `edgeStyle` in https://github.com/maxGraph/maxGraph/pull/77/files#diff-4c2458380e50c967c70d7afe819dc7412180f9f817043f27441de3498e4d0479
So `EdgeHandler` and `ElbowEdgeHandler` should be updated instead of using a new property that is never set elsewhere.

2022-02-18 05:43 UTC, tbouffard commented
I have been able to detect the issue by also running `tsc -p packages/core/tsconfig.json` from the project root, so I suggest we run this command as part of the GH Actions build.

2022-02-18 15:18 UTC, cd-yang commented
I removed `edge` from `CellStateStyles`

2022-02-20 01:05 UTC, junsikshim approved these changes

2022-02-20 10:18 UTC, tbouffard commented
Thanks @cd-yang for the changes, this looks fine now.
I am first going to create a Pull Request to reproduce the TSC errors with the GitHub Actions. Then I will merge your Pull Request which should fix the issue.
That way, we will ensure that the TSC errors won't appear without prior notice.

2022-02-20 16:42 UTC, tbouffard approved these changes

2022-02-20 16:44 UTC, merged