Examples fixed
maxGraph/maxGraph pull request #88
Opened 2022-06-01 04:09 UTC by gelvidge

**Summary**
Fixes majority of html examples.  Some small bugs may remain but 99% ok

**Description for the changelog**
Updates example html files and fixes bugs in core code that were found when testing

**Other info**

2022-06-06 03:38 UTC, junsikshim reviewed
Nice work!

I had to remove `NODE_OPTIONS=--openssl-legacy-provider` to make it run though, people with older versions of node (< 17) would face this problem.

A couple of things to comment on.
- Please run prettier on all the files so that the styles stay the same.
- I think IDE configuration files should be excluded from git repository(add to .gitignore), but it's up for debate.

Thanks!

2022-06-06 03:38 UTC, junsikshim commented on packages/core/src/view/GraphDataModel.ts
> +    return cell != null  && this.isRoot(cell.getParent());
If `cell` can be null or undefined, I think it's better change the method signature,
perhaps something like `isLayer(cell?: Cell)`.

2022-06-06 03:38 UTC, junsikshim commented on packages/core/src/view/handler/SelectionHandler.ts
> +  guidesEnabled = true;
If `guidesEnabled` should be `true` by default, please update the comments above. :)

2022-06-06 03:38 UTC, junsikshim commented on packages/core/src/view/handler/SelectionHandler.ts
> +  maxLivePreview = 50;
Like above, please change the comment accordingly if the default value must change.

2022-06-06 03:38 UTC, junsikshim commented on packages/html/stories/Clipboard.stories.js
> +          for (var i = 0; i < childCount; i++)
Let's get rid of `var`s. :)

2022-06-06 03:38 UTC, junsikshim commented on packages/html/stories/ExtendCanvas.stories.js
> +  container.style.height = '241px';
It'd be great if we can set the pixel values using storybook arguments.

2022-06-07 05:24 UTC, tbouffard requested changes
Thanks for sharing this Pull Request. This is a lot of work.
I am pretty sure that the Pull Request contains a lot of valuable work but it is too large to review.
It also contains too much unwanted formatting changes that makes it hard to read.

There are also some logic changes that requires to be discussed because I don't understand why they are needed. I don't have time to look at all commits to try to find where they could be required.
The lib has no automatic tests, and examples don't cover all use cases. It is also very easy to fix an example and break another one. The current proposal also contains several default changes that need to be discussed.

I suggest to split the work into several smaller Pull Requests: start with examples that only require storybook files changes. That way, we can review and merge working examples quickly and have more time to discuss tricky subjects

2022-06-07 05:24 UTC, tbouffard commented on package.json
> +
Extra change

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/serialization/Codec.ts
> +    //****Edit note - there may be other classes needed here????******
??

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/serialization/Codec.ts
> +        if (ctor == undefined) console.log(node.nodeName)
Please do proper Error management

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/types.ts
> +  imageVerticalAlign?: VAlignValue;
For indicator only? There was no need for this in the original mxGraph code, why do we need this now?

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/util/cloneUtils.ts
> +       if (!shallow && typeof obj[i] === 'object') {
Extra change + formatting issue

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/util/styleUtils.ts
> +          const styleClone =clone(style)
Why changing this?

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/Graph.ts
> +      if (newParent == null || !this.getDataModel().contains(newParent) || newParent.isCollapsed())
Let's review mxgraph original code or explain why you need to change the logic here.

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/canvas/SvgCanvas2D.ts
> -    if (!this.node) return;
Check original mxgraph implementation, I don't understand why we need to change the logic

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/handler/EdgeHandler.ts
> +
extra break line

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/handler/SelectionHandler.ts
> +  guidesEnabled = true;
Why changing defaults? this impacts all users of the lib and not only examples

2022-06-07 05:24 UTC, tbouffard commented on packages/html/package.json
> +    "dev": "cross-env NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 8901 ./public"
Please revert this: see #74 and https://github.com/maxGraph/maxGraph/discussions/64#discussioncomment-1968814

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/util/Utils.ts
> +//getBBox of SVG element before rendered in DOM
please write proper JSDoc

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/canvas/SvgCanvas2D.ts
>          );
I am pretty sure the previous implementation cames from the orignal mxGraph.
There are a lot of place where there are `+1` on position, width or height. It is very hard to do the review here. I don't have time to dig into the 52 commits to find which example may need the change and how this change impacts other examples.

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/mixins/ConnectionsMixin.ts
> +      perimeter = edge.style[source ? 'exitPerimeter' : 'entryPerimeter'] || true;
please don't change defaults

2022-06-07 05:24 UTC, tbouffard commented on packages/core/src/view/mixins/FoldingMixin.ts
> +Client.imageBasePath = '/images'
You are changing the configuration here and this impacts all users of the lib, not only the example.

2022-06-07 09:24 UTC, gelvidge commented
Thanks both for reviewing and thanks for the feedback. I'll look into seeing how the PR can be improved by splitting and tidying up some of the formatting

2022-06-08 07:05 UTC, tbouffard commented
@gelvidge hi, I will have some time on next Thursday to work on the project. I can try to cherry-pick some commits that quickly fix the examples in a dedicated PR.
Please let me know

2022-06-17 10:55 UTC, aminosbh commented
@gelvidge we are currently on the process of changing the license of this project to the standard Apache 2.0 license (see #89). Do you agree to use the Apache 2.0 license on your contribution ?

2022-06-20 23:09 UTC, gelvidge commented
Yes that is OK. I will aim to get around to submitting the new commits soon but all my contributions can be under Apache v2

2022-10-23 07:38 UTC, tbouffard commented
@gelvidge hi, do you still plan to recreate some PR based on the fixes proposed here?
@mayorovad started fixing some stories and some are already merged. That's why there is some merge conflicts here.

So I suggest you synchronize together if you both want to set new stories.

2024-04-12 07:39 UTC, tbouffard commented
This PR is kept opened on purpose even if it won't be merged. There is no need to update it, nor rebase it, as it it too large.

However, it contains a lot of valuable information and fixes. It can be used as a source of information to create new focused and small PR about a single topic.

2024-10-13 15:17 UTC, tbouffard commented
Closing this PR.
It will be used to pick some changes when fixing remaining problems in stories. See #505.

2024-10-13 15:17 UTC, closed without merging